# Living Room

- platform: group
  name: Living Room Uplighters
  entities:
    - light.kitchen_uplighter
    - light.dining_table_uplighter

- platform: group
  name: Living Room Ceiling
  entities:
    - light.living_room_ceiling_left
    - light.living_room_ceiling_right

# Bedroom
- platform: group
  name: Bedside
  entities:
    - light.bedside_window
    - light.bedside_door
