- platform: magicbluelight
  name: Spare Bedroom Bedside 
  address: f8:1d:78:60:c0:52
  version: 10

- platform: magicbluelight
  name: Spare Bedroom Ceiling 
  address: f8:1d:78:62:98:6f
  version: 10

- platform: magicbluelight
  name: Not Used 1
  address: f8:1d:78:60:8C:35
  version: 10

- platform: magicbluelight
  name: Not Used 2
  address: f8:1d:78:60:c6:25
  version: 10


