- platform: magicbluelight
  name: Spare Bedroom Bedside 
  address: f8:1d:78:60:c0:52
  version: 10

- platform: magicbluelight
  name: Spare Bedroom Ceiling 
  address: f8:1d:78:62:98:6F
  version: 10

- platform: magicbluelight
  name: Hallway Entrance
  address: f8:1d:78:60:8C:35
  version: 10

- platform: magicbluelight
  name: Hallway Corridoor
  address: f8:1d:78:60:C6:25
  version: 10


