- id: '1545851949432'
  alias: Sleep music
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    to: Nightf
  condition: []
  action:
  - service: light.turn_on
    data:
      brightness: 2
    entity_id: light.test_light
  - service: media_player.shuffle_set
    data:
      shuffle: true
    entity_id: media_player.spotify
  - service: media_player.play_media
    data:
      media_content_type: playlist
      media_content_id: spotify:user:spotify:playlist:37i9dQZF1DWZd79rJ6a7lp
    entity_id: media_player.spotify
- id: '1545851949438'
  alias: Bedtime Lights
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    to: 'Night'
  condition: []
  action:
  - service: script.turn_on
    entity_id: script.bedtime
- id: '3545251949432'
  alias: Workday Morning Energise Routine
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    from: Night
    to: Morning
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.bedroom_ceiling
    data:
      brightness_pct: 1
      kelvin: 2000
  - service: light.turn_on
    entity_id: light.bedroom_ceiling
    data:
      brightness_pct: 10
      kelvin: 2000
      transition: 60
  - delay: '00:00:60'
  - service: light.turn_on
    entity_id: light.bedside_door
    data:
      brightness_pct: 1
      kelvin: 2000
  - service: light.turn_on
    entity_id: light.bedside_window
    data:
      brightness_pct: 1
      kelvin: 2000
  - delay: '00:00:10'
  - service: light.turn_on
    entity_id: light.living_room
    data:
      brightness_pct: 100
      kelvin: 6500
      transition: 60
  - service: light.turn_on
    entity_id: light.bedroom
    data:
      brightness_pct: 100
      kelvin: 6500
      transition: 900
- id: '3545251949409'
  alias: Lights off during daytime
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    from: Morning
    to: Day
  condition:
    condition: state
    entity_id: 'binary_sensor.workday_sensor'
    state: 'on'
  action:
  - delay: '00:03:00'
  - service: light.turn_off
    entity_id: light.bedroom
    data:
      transition: 120
  - service: light.turn_off
    entity_id: light.living_room
    data:
      transition: 120
- id: '2545251249409'
  alias: Switch off heating at night
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    from: Evening
    to: Night
  action:
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
        temperature: 15
- id: '2545251149209'
  alias: Switch on hallway in evening
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    from: Day
    to: Evening
  action:
  - service: light.turn_on
    entity_id:
    - light.hallway
    data:
        brightness: 100
- id: '2545211239409'
  alias: Switch on heating in morning
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    from: Night
    to: Morning
  action:
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
        temperature: 20
