# Wake up routine
#- id: '3545251949432'
#  alias: Workday Morning Energise
#  trigger:
#  - at: '09:00:00'
#    platform: time
#  action:
#  - service: script.turn_on
#    entity_id: script.wakeup
# Summer: Switch lights off during day time (provided sun is up)
- id: '3545251949409'
  alias: Lights off during daytime
  trigger:
  - at: '10:00:00'
    platform: time
  condition:
    condition: sun
    after: sunrise
    after_offset: "00:30:00"
  action:
  - service: light.turn_off
    entity_id: light.bedroom
    data:
      transition: 120
  - service: light.turn_off
    entity_id: light.living_room
    data:
      transition: 120
      
# Winter: Switch lights off after sunrise (provided it is daytime)
- id: '3545251949449'
  alias: Lights off during daytime
  trigger:
  - platform: sun
    # Possible values: sunset, sunrise
    event: sunrise
    # trigger 45 minutes after sunrise.
    offset: "00:45:00"
  condition:
     alias: "After 10am"
     condition: time
     after: "10:00:00"
  action:
  - service: light.turn_off
    entity_id: 
      - light.bedroom
      - light.living_room
    data:
      transition: 120

# Update TV Volume
- id: '1001233314237'
  alias: TV Volume
  trigger:
    platform: state
    entity_id: media_player.tv
  action:
    service: shell_command.set_tv_volume

# Turn on/off speakers when TV turns on/off
- id: '1001233314117'
  alias: Turn on speakers when TV turned on
  trigger:
    platform: state
    entity_id: media_player.tv
    to: 'on'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.speakers
- id: '1001233314136'
  alias: Turn off speakers when tv turned off
  trigger:
    platform: state
    entity_id: media_player.tv
    to: 'off'
    for: "00:02:00"
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.speakers


# Turn off lights when I leave home
- id: '1333233314117'
  alias: Turn off lights when I leave home
  trigger:
    platform: state
    entity_id:
    - device_tracker.ble_de_08_b9_2e_1f_58
    - device_tracker.ble_e4_ca_ad_1b_fe_95
    to: 'not_home'
  condition:
    condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.ble_de_08_b9_2e_1f_58
      state: 'not_home'
    - condition: state
      entity_id: device_tracker.ble_e4_ca_ad_1b_fe_95
      state: 'not_home'
  action:
  - service: light.turn_off
    data:
      area_id:
      - bedroom
      - living_room


# Turn on lights when I get home in the dark
- id: '1001233314129'
  alias: Turn on lights when I get home in the dark
  trigger:
    platform: state
    entity_id: binary_sensor.pir_sensor
    to: 'on'
  condition:
    alias: "Sun down"
    condition: state  # from sunset until sunrise
    entity_id: sun.sun
    state: "below_horizon"
  action:
  - service: light.turn_on
    data:
      area_id:
      - living_room
