# Start the bedtime script when it becomes night.
- id: '1545851949438'
  alias: Bedtime
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    to: Night
  condition: []
  action:
  - service: script.turn_on
    entity_id: script.bedtime
# Wake up routine
- id: '3545251949432'
  alias: Workday Morning Energise
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    from: Night
    to: Morning
  action:
  - service: script.turn_on
    entity_id: script.wakeup
# Summer: Switch lights off during day time (provided sun is up)
- id: '3545251949409'
  alias: Lights off during daytime
  trigger:
    platform: state
    entity_id: sensor.day_phase
    from: Morning
    to: Day
  condition:
    condition: sun
    after: sunrise
    after_offset: "00:30:00"
  action:
  - service: light.turn_off
    entity_id: light.bedroom
    data:
      transition: 120
  - service: light.turn_off
    entity_id: light.living_room
    data:
      transition: 120
      
# Winter: Switch lights off after sunrise (provided it is daytime)
- id: '3545251949409'
  alias: Lights off during daytime
  trigger:
  - platform: sun
    # Possible values: sunset, sunrise
    event: sunrise
    # trigger 45 minutes after sunrise.
    offset: "00:45:00"
  - platform: state
    entity_id: sensor.day_phase
    from: Morning
    to: Day
  condition:
    condition: state
    entity_id: sensor.day_phase
    state: Day
  action:
  - service: light.turn_off
    entity_id: 
      - light.bedroom
      - light.living_room
      - light.hallway
    data:
      transition: 120
- id: '2545251249409'
  alias: Switch off heating at night
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    from: Evening
    to: Night
  action:
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
        temperature: 15
- id: '2545251149209'
  alias: Switch on hallway in evening
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    from: Day
    to: Evening
  action:
  - service: light.turn_on
    entity_id:
    - light.hallway
    data:
        brightness: 50
- id: '2545211239409'
  alias: Switch on heating in morning
  trigger:
  - entity_id: sensor.day_phase
    platform: state
    from: Night
    to: Morning
  action:
  - service: climate.set_temperature
    entity_id: climate.living_room
    data:
        temperature: 20
- id: '1557251710350'
  alias: Arrive at work
  trigger:
  - platform: zone
    entity_id: device_tracker.tom_th
    zone: zone.work
    event: enter  # or "leave"
  condition:
  - after: '07:00:00'
    before: '11:00:00'
    condition: time
  action:
  - event: ARRIVED_AT_WORK
    event_data: {}
- id: '1557260814256'
  alias: Leave Work Alarm
  trigger:
  - at: 09:30:00
    platform: time
  condition:
  - condition: zone
    entity_id: device_tracker.tom_th
    zone: zone.home
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: light.turn_on
    data:
      entity_id: light.living_room
      flash: long
- id: '1557233314252'
  alias: Fish Tank On in morning
  trigger:
  - at: '08:30:00'
    platform: time
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.fish_tank
- id: '1557233314237'
  alias: Fish Tank Off at night
  trigger:
  - at: '22:00:00'
    platform: time
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.fish_tank
      
# Update TV Volume
- id: '1001233314237'
  alias: TV Volume
  trigger:
    platform: state
    entity_id: media_player.tv
  action:
    service: shell_command.set_tv_volume

# Turn on speakers when TV turns on
- id: '1001233314117'
  alias: Turn on speakers when TV turned on
  trigger:
    platform: state
    entity_id: media_player.tv
    to: 'on'
  action:
  - service: switch.turn_on
    data:
      entity_id: switch.living_room_speakers
- id: '1001233314136'
  alias: Turn off speakers when tv turned off
  trigger:
    platform: state
    entity_id: media_player.tv
    to: 'off'
    for: "00:02:00"
  action:
  - service: switch.turn_off
    data:
      entity_id: switch.living_room_speakers
