homeassistant:
  name: Home
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: 24
  unit_system: metric
  time_zone: Europe/London

  customize: !include_dir_merge_named configuration/customize
  packages: !include_dir_merge_named configuration/package
  
lovelace:
  mode: yaml

# Enablers
browser:
cloud: !include configuration/cloud.yaml
config:
conversation:
discovery:
frontend:
    javascript_version: latest
map:
media_extractor:
    default_query: best
hue:
    bridges:
        - host: 192.168.1.31
          allow_unreachable: false
          allow_hue_groups: false
sun:
updater:
    include_used_components: true
wake_on_lan:

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influx_user
  password: !secret influx_pass
  max_retries: 3
  default_measurement: state

api:

alexa:
  smart_home:
      filter:
          include_domains:
              - light
              - climate
              - switch
          include_entities:
              - script.bedtime
              - script.goodnight
          exclude_entities:
              - automation.system_travis_build_passed
      entity_config:
          light.living_room:
              name: Living Room Lights
              display_categories: LIGHT

# History
recorder:
    db_url: !secret db_connection
    purge_interval: 1
    purge_keep_days: 14
    exclude:
        entities:
            - sensor.date

history:
    include:
        domains:
            - light
            - switch
            - sensor

logbook:
    exclude:
        domains:
            - group
        entities:
            - sensor.cpu_temp
logger:
    default: warning
    logs:
        custom_components.light.magicbluelight: debug
        magicblue.magicbluelib: debug
        homeassistant.media_player.spotify: info
        homeassistant.components.device_tracker.nmap_tracker: warn

# Text To Speech
tts:
    platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    region_name: eu-west-1
    text_type: text
    voice: Brian

# Device Tracking
zone:
    - zone:
      name: Home
      latitude: !secret zone_home_lat
      longitude: !secret zone_home_long
      radius: 250

    - zone 2:
      name: Work
      latitude: !secret zone_work_lat
      longitude: !secret zone_work_long
      radius: 200
      icon: mdi:briefcase

http:
    cors_allowed_origins:
        - https://hassio.local:7080
    base_url: !secret hass_base_url
    ssl_certificate: !secret ssl_certificate
    ssl_key: !secret ssl_key
    api_password: !secret api_password
    trusted_networks:
        - 127.0.0.1
        - 192.168.0.0/24
        - 192.168.1.0/24

device_tracker:
  - platform: nmap_tracker
    hosts:
      - 192.168.0.6
      - 192.168.0.9

ifttt: 
    key: !secret ifttt_key

notify:
  - platform: html5
    name: notify
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id

# Components
automation: !include automations.yaml
automation old: !include_dir_merge_list configuration/automation
binary_sensor: !include_dir_merge_list configuration/binary_sensor
climate: !include_dir_merge_list configuration/climate
group: !include_dir_merge_named configuration/group
history_graph: !include_dir_merge_named configuration/history_graph
input_boolean: !include_dir_merge_named configuration/input_boolean
light: !include_dir_merge_list configuration/light
media_player: !include_dir_merge_list configuration/media_player
scene: !include_dir_merge_list configuration/scene
script: !include_dir_merge_named configuration/script
sensor: !include_dir_merge_list configuration/sensor
switch: !include_dir_merge_list configuration/switch
weather: !include_dir_merge_list configuration/weather
