homeassistant:
  name: Home
  latitude: !secret zone_home_lat
  longitude: !secret zone_home_long
  elevation: 24
  unit_system: metric
  time_zone: Europe/London

  customize: !include_dir_merge_named configuration/customize
  packages: !include_dir_merge_named configuration/package
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - 192.168.1.0/24
        - 127.0.0.1
        - fd00::/8
  
lovelace:
  mode: yaml

# Enablers
browser:
cloud: !include configuration/cloud.yaml
config:
conversation:
discovery:
frontend:
map:
media_extractor:
    default_query: best
sun:
updater:
    include_used_components: true
wake_on_lan:

#influxdb:
#  host: a0d7b954-influxdb
#  port: 8086
#  database: homeassistant
#  username: !secret influx_user
#  password: !secret influx_pass
#  max_retries: 3
#  default_measurement: state

api:

alexa:
  smart_home:
      endpoint: https://api.eu.amazonalexa.com/v3/events
      client_id: !secret alexa_skill_messaging_client_id
      client_secret: !secret alexa_skill_messaging_secret
      filter:
          include_domains:
              - light
              - climate
              - switch
          include_entities:
              - script.bedtime
              - script.goodnight
          exclude_entities:
              - automation.system_travis_build_passed
      entity_config:
          light.living_room:
              name: Living Room Lights
              display_categories: LIGHT
      locale: en-GB

# History
recorder:
    db_url: !secret db_connection
    purge_keep_days: 7
    exclude:
        domains:
            - sun
            - weather
        entities:
            - sensor.date
            - sensor.date_time
            - sensor.weather_symbol

history:
    include:
        domains:
            - light
            - switch
            - sensor

logbook:
    exclude:
        domains:
            - group
        entities:
            - sensor.cpu_temp
logger:
    default: warning
    logs:
        custom_components.light.magicbluelight: debug
        magicblue.magicbluelib: debug
        homeassistant.components.device_tracker.nmap_tracker: warn

# Text To Speech
tts:
    platform: amazon_polly
    aws_access_key_id: !secret aws_access_key_id
    aws_secret_access_key: !secret aws_secret_access_key
    base_url: https://hassio.local:8123
    region_name: eu-west-1
    text_type: text
    voice: Brian

# Device Tracking
zone:
    - name: Home
      latitude: !secret zone_home_lat
      longitude: !secret zone_home_long
      radius: 250

http:
    cors_allowed_origins:
        - https://hassio.local:7080
    ssl_certificate: !secret ssl_certificate
    ssl_key: !secret ssl_key

ifttt: 
    key: !secret ifttt_key

notify:
  - platform: html5
    name: notify
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
#  - platform: webostv
#    host: 192.168.1.25
#    name: livingroom_tv
#    filename: webostv.conf

# TP Link Smart Plugs
tplink:
  discovery: false
  switch:
    - host: 192.168.1.19
    - host: 192.168.1.30
    - host: 192.168.1.41

# Webcam
ffmpeg:

camera: 
  - platform: ffmpeg
    input: /dev/video0
    name: fish_tank
    
# LG TV
webostv:
  host: 192.168.1.16
  name: TV
  turn_on_action:
      service: wake_on_lan.send_magic_packet
      data:
          mac: "20:3D:BD:97:4D:FC"
  customize:
      sources:
          - livetv
          - youtube
          - iplayer
          - netflix
          - component

spotify:
  client_id: !secret spotify_client_id
  client_secret: !secret spotify_client_secret

shell_command:
  set_tv_volume: './set_tv_volume.sh {{  (78 * (10**( -2.5 * (state_attr("media_player.tv", "volume_level") * (1 - state_attr("media_player.tv", "is_volume_muted") | int)) | float))) | round(0) | int }}'

device_tracker:
  - platform: bluetooth_le_tracker
    track_new_devices: False
    
system_health:
  
# Components
automation: !include automations.yaml
automation old: !include_dir_merge_list configuration/automation
binary_sensor: !include_dir_merge_list configuration/binary_sensor
climate: !include_dir_merge_list configuration/climate
group: !include_dir_merge_named configuration/group
input_boolean: !include_dir_merge_named configuration/input_boolean
light: !include_dir_merge_list configuration/light
media_player: !include_dir_merge_list configuration/media_player
scene: !include_dir_merge_list configuration/scene
script: !include_dir_merge_named configuration/script
sensor: !include_dir_merge_list configuration/sensor
switch: !include_dir_merge_list configuration/switch
weather: !include_dir_merge_list configuration/weather
