title: Home
views:
    - title: Main
      icon: mdi:home
      path: home
      badges:
        - sensor.day_phase
      cards:
        - type: thermostat
          entity: climate.living_room
        - type: entities
          title: Rooms
          entities:
            - light.living_room
            - entity: light.bedroom
              name: Main Bedroom
        - type: sensor
          entity: sensor.day_phase
        - type: history-graph
          title: "Presence"
          entities:
            - binary_sensor.pir_sensor
            - binary_sensor.motion_detected
            - binary_sensor.should_heat
        - type: media-control
          entity: media_player.spotify
        - type: entities
          title: "Should Heat"
          show_header_toggle: false
          entities:
              - binary_sensor.should_heat

    - title: Living Room
      path: living_room
      icon: mdi:sofa
      cards:
        - type: horizontal-stack
          cards:
            - type: light
              entity: light.living_room_uplighters
              name: Uplighters
            - type: light
              entity: light.living_room_ceiling
              name: Ceiling
        - type: entities
          title: Lights
          entities:
            - light.living_room_ceiling_left
            - light.living_room_ceiling_right
            - light.kitchen_uplighter
            - light.dining_table_uplighter
        - type: entity-button
          entity: switch.living_room_speakers
        - type: history-graph
          title: "Living Room"
          entities:
            - sensor.living_room_temperature
            - switch.heater

        - type: thermostat
          entity: climate.living_room
        - type: media-control
          entity: media_player.tv
        - type: media-control
          entity: media_player.chromecast
          
    - title: Bedroom
      path: bedroom
      icon: mdi:hotel
      cards:
        - type: horizontal-stack
          cards:
            - type: light
              entity: light.bedside
              name: Bedside
            - type: light
              entity: light.bedroom_ceiling
              name: Ceiling
        - type: entities
          title: Lights
          entities:
            - light.bedroom_ceiling
            - light.bedside_door
            - light.bedside_window
        - type: entities
          entities:
            - entity: scene.bedtime
              icon: mdi:power-sleep
        - type: history-graph
          title: "Bedroom Temperature"
          entities:
            - sensor.bedroom_temperature

    - title: System
      path: system
      icon: mdi:wrench
      cards:
        - type: sensor
          entity: sensor.travis_build_status
        - type: sensor
          entity: sensor.day_phase
        - type: sensor
          entity: sensor.disk_use_percent
        - type: entities
          title: Links
          show_header_toggle: false
          entities:
            - type: weblink
              name: Router
              icon: mdi:ethernet
              url: http://192.168.1.1
            - type: weblink
              name: Travis
              icon: mdi:worker
              url: https://travis-ci.com/tomh05/hassio-config
            - type: weblink
              name: Node Red
              icon: mdi:sitemap
              url: https://tomh05hassio.duckdns.org:1880/
            - type: weblink
              name: Pi Hole
              icon: mdi:block-helper
              url: http://hassio.local
    - title: Plan
      path: plan
      panel: false
      icon: mdi:floor-plan
      cards:
        - type: picture-elements
          image: /local/floorplan.png
          elements:
              - type: state-icon
                tap_action:
                    action: toggle
                entity: light.bedroom_ceiling
                style:
                    top: 16%
                    left: 82%
              - type: state-icon
                tap_action:
                    action: toggle
                entity: light.bedside_window
                style:
                    top: 33%
                    left: 93%
              - type: state-icon
                tap_action:
                    action: toggle
                entity: light.bedside_door
                style:
                    top: 33%
                    left: 76%
              - type: state-label
                entity: sensor.bedroom_temperature
                style:
                    top: 10%
                    left: 85%
              - type: state-icon
                tap_action:
                    action: toggle
                entity: light.kitchen_uplighter
                style:
                    top: 8%
                    left: 34%
              - type: state-icon
                tap_action:
                    action: toggle
                entity: light.dining_table_uplighter
                style:
                    top: 40%
                    left: 5%
              - type: state-icon
                tap_action:
                    action: toggle
                entity: light.living_room_ceiling_left
                style:
                    top: 56%
                    left: 20%
              - type: state-icon
                tap_action:
                    action: toggle
                entity: light.living_room_ceiling_right
                style:
                    top: 26%
                    left: 20%
              - type: state-label
                entity: sensor.living_room_temperature
                style:
                    top: 32%
                    left: 35%
              - type: state-label
                entity: sensor.outside_temperature
                style:
                    top: 90%
                    left: 25%
