meta_switches:
  name: Rooms
  icon: mdi:home-variant
  entities:
  - group.living_room_switches
  - group.lights_bedroom
  - group.lights_spare_bedroom
  - group.lights_hallway
  - group.lights_living_room
