meta_switches:
  name: Rooms
  icon: mdi:home-variant
  entities:
  - group.living_room_switches
  - group.lights_kitchen
  - group.den_switches
  - group.lights_bedroom
  - group.lights_dressing_room
  - group.lights_hallway
