# Speakers
- platform: history_stats
  name: Speakers On Last Week
  entity_id: switch.speakers
  state: "on"
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - (now().weekday() + 7) * 86400
    }}
  end: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}

- platform: history_stats
  name: Speakers On This Week
  entity_id: switch.speakers
  state: "on"
  start: >
    {{ as_timestamp(
        now().replace(hour=0).replace(minute=0).replace(second=0)
      ) - now().weekday() * 86400
    }}
  end: "{{ now() }}"

- platform: history_stats
  name: Speakers On Today
  entity_id: switch.speakers
  state: "on"
  start: >
    {{ now().replace(hour=0).replace(minute=0).replace(second=0) }}
  end: "{{ now() }}"

  #- platform: history_stats
  #name: Recent Motion
  #entity_id: binary_sensor.house_motion
  #type: count
  #state: "on"
  #end: "{{ now() }}"
  #duration:
  #  minutes: 30
