- platform: template
  sensors:
    outside_temperature:
      friendly_name: "Outside Temperature"
      unit_of_measurement: "°C"
      value_template: >
        {{ states.weather.dark_sky.attributes.temperature }}
