- platform: generic_thermostat
  name: Living Room
  heater: switch.heater
  target_sensor: sensor.living_room_temperature
  min_temp: 10
  max_temp: 23
  ac_mode: false
  target_temp: 17
  cold_tolerance: 0.3
  hot_tolerance: 0
  min_cycle_duration:
      seconds: 20
  keep_alive:
      minutes: 10
  away_temp: 15
  precision: 0.1
