- platform: template
  switches:
    bedroom_light:
      friendly_name: Bedroom Light
      value_template: '{{ is_state("light.bedroom", "on") }}'
      entity_id: light.bedroom
      turn_on:
        service: hue.hue_activate_scene
        data_template:
          group_name: Bedroom
          scene_name: '{{ states.sensor.day_phase.state }}'
      turn_off:
        service: light.turn_off
        entity_id: light.bedroom
