# TP Link Smart Plugs
- platform: tplink
  name: Living Room Speakers
  host: 192.168.1.19

- platform: tplink
  name: Heater
  host: 192.168.1.41

- platform: tplink
  name: Fish Tank 
  host: 192.168.1.30
