- platform: template
  sensors:
    # True if temperature is too low ( < 15 deg C)
    cold_outside:
      entity_id:
        - weather.dark_sky
      value_template: "{{states.weather.dark_sky.attributes.temperature|float < 10}}" 
 
    motion_detected:
      friendly_name: Motion detected
      delay_off:
        minutes: 15
      entity_id:
        - binary_sensor.living_room_motion
      value_template: "{{is_state('binary_sensor.living_room_motion', 'on')}}"

- platform: bayesian
  name: 'Should Heat'
  prior: 0.4
  observations:
      - entity_id: 'binary_sensor.motion_detected'
        # probability of motion sensor being triggered given we should have heating on
        prob_given_true: 0.6
        # probability of motion sensor being triggered given we shouldn't have heating on
        prob_given_false: 0.1
        platform: 'state'
        to_state: 'on'
      - entity_id: sensor.day_phase
        # probability of it being night given we should have heating on
        prob_given_true: 0.1
        # probability of it being night given we shouldn't have heating on
        prob_given_false: 0.5
        platform: 'state'
        to_state: 'Night'
      - entity_id: sensor.day_phase
        # probability of it being evening, given we want heating on
        prob_given_true: 0.15
        # probability of it being evening, given we don't want heating on
        prob_given_false: 0.05
        platform: 'state'
        to_state: 'Evening'
      - entity_id: binary_sensor.cold_outside
        # probability of it being cold outside, given we want heating on
        prob_given_true: 0.7
        # probability of it being cold outside, given we don't want heating on
        prob_given_false: 0.3
        platform: 'state'
        to_state: 'on'
